Fix GitHub Actions
Parser enable

Fix include on symtest

Minor? Changes?

Make still doesn't work for parser

fixed returns references

missing $(SRC) added

fixed undefined reference to argumentsNext

Attempt to fix TERM evn var error